
import {
  WrapText,
  CaseSensitive,
  Calculator,
  FileJson,
  Fingerprint,
  Shrink,
  Palette,
  KeyRound,
  Clock,
  ClipboardType,
  Settings2,
  Replace,
  Sigma,
  Rows,
  Columns,
  Binary,
  Hash,
  ShieldCheck,
  Timer,
  Sparkles,
  Wand2,
  Code,
  Paintbrush,
  Shuffle,
  Lock,
  Gauge,
  BookText,
  FileCode,
  Link,
  Search,
  GitBranch, // Added for AI Commit Message Writer
  Database,
  FileTerminal,
  Puzzle,
  SquareCode,
  Component,
  Layers3,
  Workflow,
  FileSymlink,
  FolderGit2,
  Pipette,
  BoxSelect,
  Type,
  TextCursorInput,
  ListRestart,
  ListCollapse,
  ScanLine,
  ALargeSmall,
  Text,
  FileLock2,
  Eraser,
  Bed, 
  Moon, 
  Info, 
  Copy as CopyIcon, 
  CalendarPlus,
  Lightbulb, // Added for AI Blog Post Idea Generator
  Image, // Added for AI Image Alt Text Generator
  Newspaper, // Added for potential use (e.g. AI Text Summarizer, but using ScanLine for now)
  GitCommit, // Alternative for Commit Message Writer
} from 'lucide-react';

export const Icons = {
  WrapText,
  CaseSensitive,
  Calculator,
  FileJson,
  Fingerprint,
  Shrink,
  Palette,
  KeyRound,
  Clock,
  ClipboardType,
  Settings2,
  Replace,
  Sigma,
  Rows,
  Columns,
  Binary,
  Hash,
  ShieldCheck,
  Timer,
  Sparkles,
  Wand2,
  Code,
  Paintbrush,
  Shuffle,
  Lock,
  Gauge,
  BookText,
  FileCode,
  Link,
  Search,
  GitBranch,
  Database,
  FileTerminal,
  Puzzle,
  SquareCode,
  Component,
  Layers3,
  Workflow,
  FileSymlink,
  FolderGit2,
  Pipette,
  BoxSelect,
  Type,
  TextCursorInput,
  ListRestart,
  ListCollapse,
  ScanLine,
  ALargeSmall,
  Text,
  FileLock2,
  Eraser,
  Bed,
  Moon,
  Info,
  CopyIcon,
  CalendarPlus,
  Lightbulb,
  Image,
  Newspaper,
  GitCommit,
  NymLogo: (props: React.SVGProps<SVGSVGElement>) => (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5" />
    </svg>
  ),
};

export type IconName = keyof typeof Icons;
