
import {
  WrapText,
  CaseSensitive,
  Calculator,
  FileJson,
  Fingerprint,
  Shrink,
  Palette,
  KeyRound,
  Clock,
  ClipboardType,
  Settings2,
  Replace,
  Sigma,
  Rows,
  Columns,
  Binary,
  Hash,
  ShieldCheck,
  Timer,
  Sparkles,
  Wand2,
  Code,
  Paintbrush,
  Shuffle,
  Lock,
  Gauge,
  BookText,
  FileCode,
  Link as LinkIcon, // Renamed to avoid conflict with NextLink
  Search,
  GitBranch,
  Database,
  FileTerminal,
  Puzzle,
  SquareCode,
  Component,
  Layers3,
  Workflow,
  FileSymlink,
  FolderGit2,
  Pipette,
  BoxSelect,
  Square,
  Type,
  TextCursorInput,
  ListRestart,
  ListCollapse,
  ScanLine,
  ALargeSmall,
  Text,
  FileLock2,
  Eraser,
  Bed,
  Moon,
  Info,
  Copy as CopyIcon,
  CalendarPlus,
  Lightbulb,
  Image,
  Newspaper,
  GitCommit,
  Thermometer,
  Ruler,
  Globe,
  ThumbsUp,
  Users,
  Slash,
  Star, // Added Star
  Heart, // Added Heart (filled, for favorites)
  HelpCircle,
  MessageSquare,
  Zap,
  CheckCircle,
  Angry,
  Frown,
  Meh,
  Smile,
  Laugh,
  Loader2,
  Upload,
} from 'lucide-react';

export const Icons = {
  WrapText,
  CaseSensitive,
  Calculator,
  FileJson,
  Fingerprint,
  Shrink,
  Palette,
  KeyRound,
  Clock,
  ClipboardType,
  Settings2,
  Replace,
  Sigma,
  Rows,
  Columns,
  Binary,
  Hash,
  ShieldCheck,
  Timer,
  Sparkles,
  Wand2,
  Code,
  Paintbrush,
  Shuffle,
  Lock,
  Gauge,
  BookText,
  FileCode,
  Link: LinkIcon,
  Search,
  GitBranch,
  Database,
  FileTerminal,
  Puzzle,
  SquareCode,
  Component,
  Layers3, // For categories nav
  Workflow,
  FileSymlink,
  FolderGit2,
  Pipette,
  BoxSelect,
  Square,
  Type,
  TextCursorInput,
  ListRestart,
  ListCollapse,
  ScanLine,
  ALargeSmall,
  Text,
  FileLock2,
  Eraser,
  Bed,
  Moon,
  Info, // For about nav, sleep cycle info
  CopyIcon,
  CalendarPlus,
  Lightbulb,
  Image,
  Newspaper,
  GitCommit,
  Thermometer,
  Ruler,
  Globe,
  ThumbsUp,
  Users,
  Slash,
  Star, // For Favorites nav & empty state
  Heart, // For favorite toggle
  HelpCircle,
  MessageSquare, // For contact nav
  Zap,
  CheckCircle,
  Angry,
  Frown,
  Meh,
  Smile,
  Laugh,
  Loader2, // For loading states
  Upload, // For image upload button
  NymLogo: (props: React.SVGProps<SVGSVGElement>) => (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5" />
    </svg>
  ),
};

export type IconName = keyof typeof Icons;
